import { ArrowLeft, BookOpen, AlertTriangle, FileText, CheckCircle2, Mail } from 'lucide-react'
import type { Page } from '../App'

type Props = {
  onNavigate: (page: Page) => void
}

export function TermsOfServicePage({ onNavigate }: Props) {
  return (
    <div className="animate-entrance max-w-4xl mx-auto py-6 px-4 sm:px-6">
      <div className="mb-6 flex items-center justify-between border-b border-slate-200/80 pb-4">
        <button
          type="button"
          onClick={() => onNavigate('dashboard')}
          className="inline-flex items-center gap-2 px-3.5 py-2 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 font-bold text-xs shadow-sm transition-all"
        >
          <ArrowLeft size={16} />
          <span>Back to Workspace</span>
        </button>

        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-indigo-50 border border-indigo-200 text-indigo-800 text-xs font-semibold">
          <BookOpen size={14} className="text-indigo-600" />
          <span>Production Terms of Service</span>
        </div>
      </div>

      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 sm:p-10 space-y-8 text-slate-700">
        <div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight mb-2">
            Terms of Service
          </h1>
          <p className="text-xs font-semibold text-slate-500">
            Product Manual Assistant &bull; Effective Date: October 2026
          </p>
          <p className="text-xs text-indigo-600 font-bold mt-1">
            Production URL: https://manualassistant.vercel.app
          </p>
        </div>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-2">
            <CheckCircle2 size={18} className="text-indigo-600" />
            1. Acceptance of Terms
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed text-slate-600">
            By accessing or using Product Manual Assistant (&quot;the Service&quot;) at <strong className="text-slate-800">https://manualassistant.vercel.app</strong>, you agree to be bound by these Terms of Service. If you do not agree to all terms, do not access or use the application.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-2">
            <BookOpen size={18} className="text-indigo-600" />
            2. Description of Service
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed text-slate-600">
            Product Manual Assistant is an AI-assisted RAG (Retrieval-Augmented Generation) software application that enables users to upload product user manuals in PDF format, query document contents using natural language, and view generated answers accompanied by page-level citations.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-2">
            <FileText size={18} className="text-indigo-600" />
            3. User Responsibilities &amp; Content Ownership
          </h2>
          <div className="space-y-2 text-xs sm:text-sm leading-relaxed text-slate-600">
            <p><strong>Content Rights:</strong> You retain ownership of all PDF manuals and documents you upload to the Service. You represent and warrant that you have all necessary rights, licenses, and permissions to upload and process such documents.</p>
            <p><strong>Acceptable Use:</strong> You agree not to upload malicious software, corrupted files, illegal content, or documents containing confidential third-party data without authorization. You agree not to attempt to compromise, disrupt, or reverse-engineer the Service architecture.</p>
            <p><strong>File Boundaries:</strong> Uploaded documents must adhere to established system constraints (up to 10 MB per PDF file and up to 50 pages per document).</p>
          </div>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-2">
            <AlertTriangle size={18} className="text-amber-600" />
            4. AI-Generated Answers &amp; Disclaimer of Accuracy
          </h2>
          <div className="space-y-3 text-xs sm:text-sm leading-relaxed text-slate-600">
            <p><strong>AI Assistance Disclaimer:</strong> Answers generated by Product Manual Assistant are produced using artificial intelligence language models (Google Gemini) processing retrieved manual excerpts. While the Service employs context compression and explicit page citation mapping to maximize grounding accuracy, AI outputs may contain errors, omissions, or misinterpretations.</p>
            <div className="p-3.5 rounded-xl bg-amber-50/80 border border-amber-200 text-amber-900 font-medium">
              <strong className="block text-xs font-bold mb-1">Critical Notice:</strong>
              Answers provided by Product Manual Assistant are for general reference and informational guidance only. They DO NOT constitute professional engineering, electrical, medical, legal, or emergency safety advice. Always consult the physical manufacturer documentation, qualified technicians, or certified safety professionals for high-risk equipment operation.
            </div>
          </div>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-2">
            <BookOpen size={18} className="text-indigo-600" />
            5. Service Availability &amp; Third-Party Services
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed text-slate-600">
            The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis without warranties of any kind, whether express or implied. We do not guarantee continuous, uninterrupted, or error-free operation of the application.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed text-slate-600">
            The Service relies on third-party infrastructure providers including Supabase (data hosting and authentication) and Google (Gemini API and Google OAuth). We are not liable for third-party service outages or API downtime.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-2">
            <AlertTriangle size={18} className="text-indigo-600" />
            6. Limitation of Liability &amp; Termination
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed text-slate-600">
            To the maximum extent permitted by applicable law, Product Manual Assistant and its developer shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of data or equipment damage resulting from your use of or reliance on the Service.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed text-slate-600">
            We reserve the right to suspend or terminate user access to the Service at our discretion for violations of these Terms.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-2">
            <CheckCircle2 size={18} className="text-indigo-600" />
            7. Changes to Terms
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed text-slate-600">
            We reserve the right to modify or replace these Terms of Service at any time. Any changes will be posted on this page with an updated effective date.
          </p>
        </section>

        <section className="p-4 rounded-xl bg-indigo-50/60 border border-indigo-100 space-y-2">
          <h3 className="text-sm font-extrabold text-slate-900 flex items-center gap-2">
            <Mail size={16} className="text-indigo-600" />
            Contact &amp; Support
          </h3>
          <p className="text-xs text-slate-600 leading-relaxed">
            For questions regarding these Terms of Service, please contact:
          </p>
          <div className="text-xs font-semibold text-slate-800">
            Developer: <span className="text-slate-900 font-bold">Dev Verma</span><br />
            Contact Email: <a href="mailto:devverma9451@gmail.com" className="text-indigo-600 underline font-bold">devverma9451@gmail.com</a><br />
            Product Manual Assistant &bull; <a href="https://manualassistant.vercel.app" target="_blank" rel="noreferrer" className="text-indigo-600 underline font-bold">https://manualassistant.vercel.app</a>
          </div>
        </section>
      </div>
    </div>
  )
}
